(module
 (export "main" (func $main))
 (func $test (param $0 i32) (result i32)
   (block (result i32)
     (get_local $0)
     (br 0)
     (i32.const 1)
   )
 )
 (func $main (result i32)
  (i32.const 10)
  (call $test)
 )
)
